### ISSUE TITLE
not work on version: "1.3.21"?

### ISSUE THREAD

**Issue by yuomtheara** [oskarszoon/meteor-bootstrap-daterangepicker#5]
When I update to version: "1.3.21", it don't work
```js
// template
   <input type="text" id="daterange" name="daterange"/>

// js
    Template.hello.onRendered(function () {
        $('input[name="daterange"]').daterangepicker();
    });

```

**Comment by sferoze** [comment]
Its not working for me either. I get the console error moment is not a function
